CREATE TABLE TESTCHECK
(
	ID	INT PRIMARY KEY IDENTITY,
	LUONG	INT CHECK(LUONG > 3000 AND LUONG < 9000)
)
GO

INSERT dbo.TESTCHECK(LUONG)
VALUES (3000) -- LỖI VÌ PHẢI TRUYỀN VÀO SỐ > 3000 VÀ < 9000

-- CÓ THỂ TẠO CHECK Y NHƯ TẠO KHÓA CHÍNH
CREATE TABLE TESTCHECK2
(
	ID	INT PRIMARY KEY IDENTITY,
	LUONG	INT,
	CHECK(LUONG > 3000 AND LUONG < 9000)
)
GO

CREATE TABLE TESTCHECK3
(
	ID	INT PRIMARY KEY IDENTITY,
	LUONG	INT,
	CONSTRAINT CK_LUONG CHECK(LUONG > 3000 AND LUONG < 9000)
)
GO

CREATE TABLE TESTCHECK4
(
	ID	INT PRIMARY KEY IDENTITY,
	LUONG	INT
)
GO
ALTER TABLE dbo.TESTCHECK4 ADD CONSTRAINT CK_LUONG
CHECK (LUONG > 3000 AND LUONG < 9000)