CREATE DATABASE BAI08
GO
USE BAI08 
GO
-- TẠO FUNCTION
CREATE FUNCTION SUM_AB
(
	@A INT,
	@B INT
)
RETURNS INT
AS
BEGIN 
	RETURN (@A+@B);
END
GO
-- KHI CHẠY HÀM TRÊN THÌ SẼ K CHẠY ĐC NỮA VÌ NÓ ĐÃ ĐC LƯU LẠI
SELECT dbo.SUM_AB(20,5 ) AS RESULT -- GỌI HÀM
-- CÚ PHÁP XÓA FUNCTION DO USER ĐỊNH NGHĨA
DROP FUNCTION dbo.SUM_AB
GO
-- TRẢ VỀ VỊ TRÍ CỦA KÝ TỰ TRÙNG NHAU, BẮT ĐẦU TỪ VỊ TRÍ 1
SELECT CHARINDEX('BC', 'ABCDE')