-- unique: duy nhất
-- default: giá trị mặc định sẽ là...
CREATE TABLE TEST1
(
	ID	INT		UNIQUE	NOT NULL,
	NAME	NVARCHAR(250)	DEFAULT N'HOÀNG LONG'
)
GO
-- KHI ĐÃ TẠO BẢNG, ĐỔI UNIQUE-> PRIMARY KEY
ALTER TABLE dbo.TEST1 ADD PRIMARY KEY (ID)
-- TẠO PRIMARY KEY TRONG BẢNG KHÔNG PHẢI LÚC KHAI BÁO
CREATE TABLE TEST2
(
	ID	INT		NOT NULL,
	NAME	NVARCHAR(250)	DEFAULT N'HOÀNG LONG',
	PRIMARY KEY (ID) -- LÚC KHAI BÁO PHẢI CÓ NOT NULL
)
GO
-- TẠO PRIMARY KEY NGAY TRONG BẢNG MÀ ĐẶT TÊN CHO KEY ĐÓ
CREATE TABLE TEST3
(
	ID	INT		NOT NULL,
	NAME	NVARCHAR(250)	DEFAULT N'HOÀNG LONG',
	CONSTRAINT PK_TEST3, -- SAU NÀY XÓA DỄ HƠN
	PRIMARY KEY (ID) -- LÚC KHAI BÁO PHẢI CÓ NOT NULL
)
GO
-- TẠO PRIMARY KEY SAU KHI TẠO BẢNG VÀ ĐẶT TÊN CHO KEY ĐÓ
CREATE TABLE TEST4
(
	ID	INT		NOT NULL,
	NAME	NVARCHAR(250)	DEFAULT N'HOÀNG LONG'
)
GO
ALTER TABLE dbo.TEST4
ADD CONSTRAINT PK_TEST4
PRIMARY KEY (ID)
-- KHÓA CHÍNH CÓ 2 TRƯỜNG 
CREATE TABLE TEST5
(
	ID1	INT		NOT NULL,
	ID2	INT		NOT NULL,
	NAME	NVARCHAR(250)	DEFAULT N'HOÀNG LONG',
	PRIMARY KEY (ID1, ID2) -- LÚC KHAI BÁO PHẢI CÓ NOT NULL
)
GO
-- IDENTITY(START, N INCREASE) LÀ KHÓA CHÍNH
CREATE TABLE TEST6
(
	ID	INT		IDENTITY(1,1) PRIMARY KEY, -- TỰ ĐỘNG TĂNG 1 ĐƠN VỊ
	NAME	NVARCHAR(250)	DEFAULT N'HOÀNG LONG'
)
GO