CREATE DATABASE Primary_Foreign
GO
USE Primary_Foreign
GO
CREATE TABLE BOMON
(
	MABM	CHAR(10) PRIMARY KEY,
	NAME 	NVARCHAR(100) DEFAULT N'TÊN BỘ MÔN'
)
GO
CREATE TABLE LOP
(
	MALOP	CHAR(10) NOT NULL,
	NAME 	NVARCHAR(100) DEFAULT N'TÊN LỚP',
	PRIMARY KEY (MALOP)
)
GO
CREATE TABLE GIAOVIEN
(
	MAGV	CHAR(10)	NOT NULL,
	NAME	NVARCHAR(100)	DEFAULT N'TÊN GIÁO VIÊN',
	DIACHI	NVARCHAR(100)	DEFAULT N'ĐỊA CHỈ GIÁO VIÊN',
	NGAYSINH DATE,
	SEX	BIT,
-- TẠO KHÓA NGOẠI
	MABM	CHAR(10),
	FOREIGN KEY(MABM) REFERENCES dbo.BOMON(MABM)
)
GO

ALTER TABLE dbo.GIAOVIEN ADD PRIMARY KEY (MAGV)
CREATE TABLE HOCSINH
(
	MAHS	CHAR(10)	PRIMARY KEY,
	NAME 	NVARCHAR(100),
	MALOP	CHAR(10)
)
GO
-- TẠO KHÓA NGOẠI SAU KHI TẠO BẢNG
ALTER TABLE dbo.HOCSINH ADD FOREIGN KEY(MALOP) REFERENCES dbo.LOP(MALOP)
-- ALTER TABLE dbo.HOCSINH ADD CONSTRAINT FK_HS FOREIGN KEY(MALOP) REFERENCES dbo.LOP(MALOP) (DỄ XÓA, HỦY HƠN)
-- ĐỂ HỦY KHÓA THÌ: ALTER TABLE dbo.HOCSINH DROP CONSTRAINT FK_HS


	