CREATE DATABASE BAI10
GO
USE BAI10
GO

CREATE TABLE NHANVIEN
(
	ID	INT	PRIMARY KEY,
	HOTEN	NVARCHAR(250)
)
-- ĐỔI TÊN TABLE NHANVIEN -> SINHVIEN
EXEC SP_RENAME 'dbo.NHANVIEN', 'SINHVIEN'
GO
-- ĐỔI TÊN COLUMN CỦA TABLE
EXEC SP_RENAME 'dbo.SINHVIEN.ID', N'MÃ SỐ'
GO

CREATE TABLE KHOA
(
	MAKHOA	NVARCHAR(250) PRIMARY KEY,
	TENKHOA	NVARCHAR(250)
)
-- THÊM MỚI COLUMN MAKHOA VÀ NGAYSINH VÀO TABLE
ALTER TABLE SINHVIEN ADD
	-- KHÓA NGOẠI CÓ LIÊN KẾT VỚI MAKHOA CỦA TABLE KHOA
	MAKHOA	NVARCHAR(250) FOREIGN KEY REFERENCES KHOA(MAKHOA),
	NGAYSINH	DATE
GO
-- XÓA COLUMN CỦA TABLE
	-- K XÓA ĐC DO NÓ ĐANG LÀ KHÓA NGOẠI CỦA TABLE KHOA, NÊN PHẢI XÓA BÊN MAKHOA BÊN TABLE KHOA TRC
ALTER TABLE SINHVIEN DROP COLUMN MAKHOA
GO
	-- XÓA ĐC VÌ NÓ K BỊ RÀNG BUỘC
ALTER TABLE SINHVIEN DROP COLUMN NGAYSINH
GO
-- ĐỔI KIỂU DỮ LIỆU CỦA TABLE
ALTER TABLE SINHVIEN
ALTER COLUMN HOTEN VARCHAR(250)
GO
-- XÓA TOÀN BỘ DỮ LIỆU CỦA BẢNG
TRUNCATE TABLE SINHVIEN


	


