CREATE DATABASE  BAI07
GO
USE BAI07
GO 
-- KHAI BÁO BIẾN
	-- KHAI BÁO NHÌU BIẾN: DECLARE @TENBIEN1 KIEUDULIEU, @TENBIEN2 KIEUDULIEU;
DECLARE @L INT;
SET @L = 15;	-- GÁN GIÁ TRỊ CHO BIẾN
SET @L = @L * 2;
SELECT @L AS RESULT

-- BIẾN KIỂU TABLE
DECLARE @TB TABLE
(
	DID		VARCHAR(50),
	DNAME	NVARCHAR(250)
);
	-- CÓ THỂ DÙNG UPDATE, DELETE,....
INSERT INTO @TB (DID, DNAME) VALUES('123', N'VÃI XOÀI');
INSERT INTO @TB	(DID, DNAME) VALUES('321', N'XOÀI VÃI');
SELECT * FROM @TB	-- ĐÂY LÀ 1 CÂU LỆNH
/* ĐÂY LÀ 1 KHỐI LỆNH
BEGIN 
	INSERT INTO @TB (DID, DNAME) VALUES('123', N'VÃI XOÀI');
	INSERT INTO @TB	(DID, DNAME) VALUES('321', N'XOÀI VÃI');
	SELECT * FROM @TB
END */

-- CÂU LỆNH CÓ ĐIỀU KIỆN
DECLARE @N INT
SET @N = 5
IF @N = 5
	SELECT 5 AS RESULT
ELSE
	SELECT @N * 5 AS RESULT
	/* ELSE 
			BEGIN
				.....
				.....
				.....
			END
	*/
-- VÒNG LẶP
DECLARE @M INT
SET @M = 1;
WHILE @M < 100
	SET @M = @M + 1
SELECT @M AS RESULT
-- XỬ LÝ NGOẠI LỆ
/* 
BEGIN TRY
	VÙNG CHỊU GIÁM SÁT LỖI
END TRY
BEGIN CATCH
	VÙNG XỬ LÝ KHI CÓ LỖI
END CATCH
